# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dprc < Formula
  desc ""
  homepage ""
  version "0.1.0-alpha.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Arthur1/dpr/releases/download/v0.1.0-alpha.6/dprc_Darwin_arm64.tar.gz"
      sha256 "db43625a0eebb23331154e8147e7847997f9c6ee4264271bd70f1bcb69744a71"

      def install
        bin.install "dprc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Arthur1/dpr/releases/download/v0.1.0-alpha.6/dprc_Darwin_x86_64.tar.gz"
      sha256 "8cbc7ecff823e30185cff77ef65583536e8ed97795a48ed3958008c95618c137"

      def install
        bin.install "dprc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Arthur1/dpr/releases/download/v0.1.0-alpha.6/dprc_Linux_arm64.tar.gz"
      sha256 "a1378bdfb13b4ab8e0b6de9b4724930cd9268048effbaad4305b4548bac42f3c"

      def install
        bin.install "dprc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Arthur1/dpr/releases/download/v0.1.0-alpha.6/dprc_Linux_x86_64.tar.gz"
      sha256 "638796d84c565ca19bcc5ff30a4407a4ec4bead22191c2e4dbf48efb67d1968c"

      def install
        bin.install "dprc"
      end
    end
  end
end
