# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otlc < Formula
  desc ""
  homepage ""
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Arthur1/otlc/releases/download/v0.4.3/otlc_Darwin_x86_64.tar.gz"
      sha256 "8f7fdf197137f60dd0b20d7361932a33052adb3020abfb540068e208713a87d7"

      def install
        bin.install "otlc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Arthur1/otlc/releases/download/v0.4.3/otlc_Darwin_arm64.tar.gz"
      sha256 "aaf214a9ad927e3e1b2b70436ca79e1e036a82594c50f5f90613c9df3c8f9c1a"

      def install
        bin.install "otlc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arthur1/otlc/releases/download/v0.4.3/otlc_Linux_x86_64.tar.gz"
        sha256 "82de2103d2ce2167b69aa57c6b6a9a4b6fe85d90946d36937b5b5891793980f6"

        def install
          bin.install "otlc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arthur1/otlc/releases/download/v0.4.3/otlc_Linux_arm64.tar.gz"
        sha256 "bc14d46b0be3745578ed0b2bfe9f174f084762d8bd07615ea099bf13231a4c6f"

        def install
          bin.install "otlc"
        end
      end
    end
  end
end
