# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SemconviewGo < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Arthur1/semconview-go/releases/download/v0.1.0/semconview-go_Darwin_x86_64.tar.gz"
      sha256 "481e61380b7decc0fce76bda5f48400a46e79050cbb464b41650fd75e29e3100"

      def install
        bin.install "semconview-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Arthur1/semconview-go/releases/download/v0.1.0/semconview-go_Darwin_arm64.tar.gz"
      sha256 "14a0ce3eb4da47ca2864318c59877aec45074f501e22d3d541433e06b72ade04"

      def install
        bin.install "semconview-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arthur1/semconview-go/releases/download/v0.1.0/semconview-go_Linux_x86_64.tar.gz"
        sha256 "e888c052b234f71c4eb4ebfe997f6e83fa3db3f3295f105a262a8314ef47edab"

        def install
          bin.install "semconview-go"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Arthur1/semconview-go/releases/download/v0.1.0/semconview-go_Linux_arm64.tar.gz"
        sha256 "48f4f577921507a16e50b8573bf94efb93abe9b7c27ce1c1203a44da05f49205"

        def install
          bin.install "semconview-go"
        end
      end
    end
  end
end
